import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe5tZa9lwhOpzFzzIksgEXJXjGRlXbRyhQ9g&usqp=CAU"
        />
      </Head>


      <div
        style={{
          backgroundImage: "url(https://wallpaperaccess.com/full/5818333.jpg)",
          backgroundPosition: "center",
          backgroundAttachment: "fixed",
          backgroundSize: "cover",
          height:"100vh",
          display:"flex",
          justifyContent:"center",
          alignItems:"center",
          flexDirection:"column"
        }}>
          <h1 style={{fontSize:"50px"}}>Welcome to my pokedex app!</h1>
<div style={{textAlign:"center", border:"1px solid black", backgroundColor:"darkred", color:"white", padding:"10px", display:"inline-block"}}>
<Link href={'/pokemon'} >Click Me to see the app</Link>

</div>
        </div>
        
    </div>
  );
};

export default Home;
