import { useQuery } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Error from "../../components/Error";
import Loading from "../../components/Loading";
import SinglePokemon from "../../components/SinglePokemon";
import { GET_ALL_POKEMON_DATA } from "../../helpers/queries";
import { SinglePokemonProps } from "../../helpers/types";

const SelectedPokemon = () => {
  const router = useRouter();

  const { id } = router.query;

  const { data, loading, error } = useQuery(GET_ALL_POKEMON_DATA, {
    variables: {
      id,
    },
  });

  if (loading) return <Loading />;

  if (error) return <Error />;

  return (
    data &&
    !loading && (
      <>
      <Head>
        <title>#{data.pokemon_v2_pokemon[0].id} {data.pokemon_v2_pokemon[0].name}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe5tZa9lwhOpzFzzIksgEXJXjGRlXbRyhQ9g&usqp=CAU"
        />
      </Head>

       
          <SinglePokemon
            key={data.pokemon_v2_pokemon[0].id}
            height={data.pokemon_v2_pokemon[0].height}
            id={data.pokemon_v2_pokemon[0].id}
            name={data.pokemon_v2_pokemon[0].name}
            weight={data.pokemon_v2_pokemon[0].weight}
            pokemon_v2_pokemontypes={data.pokemon_v2_pokemon[0].pokemon_v2_pokemontypes}
            pokemon_v2_pokemonstats={data.pokemon_v2_pokemon[0].pokemon_v2_pokemonstats}
            pokemon_v2_pokemonabilities={data.pokemon_v2_pokemon[0].pokemon_v2_pokemonabilities}
          />

      </>
    )
  );
};

export default SelectedPokemon;
